name:                cic-hat-bar
version:             0.1.0.0
github:              "ionathanch/cic-hat-bar"
license:             BSD3
author:              "Jonathan Chan"
maintainer:          "Jonathan Chan"
copyright:           "2019 Jonathan Chan"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ionathanch/cic-hat-bar#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  cic-hat-bar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cic-hat-bar

tests:
  cic-hat-bar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cic-hat-bar
